site_name: unclean数据集合成效果对比clean数据集
theme:
  name: material
  features:
    - navigation.tabs
    - navigation.tabs.sticky

nav:
  - 语音合成模型测试: index.md
  # 在这里添加更多页面，如果需要

extra:
  social:
    - icon: fontawesome/brands/github-alt
      link: https://github.com/lunar333/vits-japanese-finetune.git